### ISSUE TITLE
Deploy 1.3

### ISSUE THREAD

**Issue by capasfield** [ExposuresProvider/cam-kp-api#558]
https://arax.ncats.io/?smartapi=1 shows that CAM-KP has 1.2 in development. 

Please deploy 1.3 of this tool into development ASAP.

**Comment by gaurav** [comment]
We now have TRAPI 1.3 in production, staging and testing at ITRB and on development at RENCI and updated on https://arax.ncats.io/?smartapi=1

Our sole working TRAPI 1.2 instance is on RENCI's intranet, and so isn't publicly accessible. If somebody needs to use it, I should be able to make it accessible fairly quickly, but I assume this isn't urgent.
